spring:
    flyway:
        schemas: benutzer
        create-schemas: true
        url: jdbc:mariadb://localhost:3307/
        user: root
        password: iamgroot
    datasource:
        url: jdbc:mariadb://localhost:3307/benutzer
        username: root
        password: iamgroot
